### ISSUE TITLE
How to run locally?

### ISSUE THREAD

**Issue by davvidbaker** [statecharts/xstate-viz#1]
Trying to run the examples locally with `npm run examples` and getting stuck.

I saw that the `examples` folder is `gitignored`–is that correct? Should there be a `package.json` in there that has a `start` script?

Thanks for xstate btw. Just started trying it out and really digging it 🤙

**Comment by davidkpiano** [comment]
Thanks! This is just a React app and I don't intend it for public use (just to be open-sourced) so I can't exactly help there.

**Comment by davvidbaker** [comment]
For sure. Thanks.

**Comment by drorspei** [comment]
Oh bummer :(
I was thinking on working on this, adding history tab and ability to go back and forth.

**Comment by davidkpiano** [comment]
@drorspei You still can! If you can get it running (should be pretty straightforward), feel free.

I just won't be spending time writing docs on this codebase, is what I'm saying. At least not yet.
