### ISSUE TITLE
Visualizer doesn't properly handle the `done.invoke.serviceName` event

### ISSUE THREAD

**Issue by amitnovick** [statecharts/xstate-viz#20]
The following Machine config fails to transition from `loading` to `sucess` state.
The transition should trigger after a service named `fetch` is invoked, i.e. on `done.invoke.fetch` event.

```js
const fetchMachine = Machine({
    id: 'fetch',
    initial: 'idle',
    context: {
      retries: 0
    },
    states: {
      idle: {
        on: {
          FETCH: 'loading'
        }
      },
      loading: {
        invoke: {
          src: 'fetch',
          onDone: 'success',
          onError: 'failure'
        }
      },
      success: {
        type: 'final'
      },
      failure: {
        on: {
          RETRY: {
            target: 'loading',
            actions: 'doSomething'
          }
        }
      }
    }
  });
```

Visualizers tried:
- older one: https://statecharts.github.io/xstate-viz/
- newer one: https://xstate.js.org/viz/

EDIT: Apparently this part is not related to the issue:
~~The following warning is printed to console when the Visualizer loads with the machine:~~
```
No service found for invocation 'fetch' in machine 'fetch'.
```

**Comment by mettjus** [comment]
The warning you reported is the normal warning that's printed by `xstate` when an invocation is reached and the corresponding service implementation (passed via the 2nd param to `Machine` or `withConfig`) has not been provided (i.e: https://codesandbox.io/s/xstate-no-service-found-for-invocation-nmsus). I think it's expected behavior.
BTW I just tried the Visualizer and I don't get the warning... 🤔 
Do you mean that currently, the Visualizer doesn't properly handle the `done.invoke.fetch` event?

**Comment by amitnovick** [comment]
> The warning you reported is the normal warning that's printed by `xstate` when an invocation is reached and the corresponding service implementation (passed via the 2nd param to `Machine` or `withConfig`) has not been provided (i.e: https://codesandbox.io/s/xstate-no-service-found-for-invocation-nmsus). I think it's expected behavior.

Ah I see! never noticed the warning before so I assumed it's somehow related

**Comment by amitnovick** [comment]
> Do you mean that currently, the Visualizer doesn't properly handle the `done.invoke.fetch` event?

Yep! that's exactly the issue.

Renamed the Issue title to that

Thanks! appreciate the help :-)

**Comment by davidkpiano** [comment]
This event is now handled. #24
