### ISSUE TITLE
Clicking on resolve on promise service does not work

### ISSUE THREAD

**Issue by alizbazar** [statecharts/xstate-viz#24]
One of the greatest powers of the statechart visualizer is being able to walk through the chart interactively emitting events by clicking on them.

However, when invoking a service that returns a promise, it's only possible to emit "reject" event, but not "resolve" one. Is there a reason for this?

Example: https://xstate.js.org/viz/?gist=54229b2f52861004ffc8a70017189391

**Comment by davidkpiano** [comment]
This now works as expected.

**Comment by alizbazar** [comment]
That's awesome! Thank you! 💯
