### ISSUE TITLE
Error: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by amitnovick** [statecharts/xstate-viz#32]
## Description
Tried to load the example [React TodoMVC `todoMachine`](https://codesandbox.io/s/xstate-todomvc-33wr94qv1?from-embed) into the Visualizer and the app crashed with the issue's title as an error logged into the `console`.

## Minimal Reproduction
[The source gist](https://gist.github.com/amitnovick/6dbc4122edab05053cc516854984a16c)

[Visualizer loaded with the gist](https://xstate.js.org/viz/?gist=6dbc4122edab05053cc516854984a16c)

**Comment by shmidt-i** [comment]
The problem is in `sendParent(ctx => ...)` notation. Function `ctx => ` is an event, and don't have `type` and `indexOf` of undefined is not available. Probably different versions of xstate in example and in viz?

**Comment by amitnovick** [comment]
> The problem is in `sendParent(ctx => ...)` notation. Function `ctx => ` is an event, and don't have `type` and `indexOf` of undefined is not available.
> 
> Upd: src/StateChartAction.tsx:97

A little confused by this, would love to get a clarification.

The `sendParent(...)` [function](https://github.com/davidkpiano/xstate/blob/master/src/actions.ts#L241) is based on `send()` [function](https://github.com/davidkpiano/xstate/blob/master/src/actions.ts#L175).

Apparently, if the first argument (`event`) provided to `sendParent` [is a function](https://github.com/davidkpiano/xstate/blob/master/src/actions.ts#L182), then the event key is assigned that function, whereas if it's not a function, it is [converted](https://github.com/davidkpiano/xstate/blob/master/src/utils.ts#L526) to an `EventObject` first.

Is what you mean that the XState-Viz is basically [evaluating](https://github.com/statecharts/xstate-viz/blob/master/src/StateChartAction.tsx#L97) `() => {}.type.indexedOf` where that evaluates to `undefined.indexedOf` which is a TypeError?

**Comment by shmidt-i** [comment]
Sorry, will try to submit a PR fixing this tomorrow, too busy at work now :)
Basically you are right and the fix is super easy: 


Change
```js
sendAction.event.type.indexOf("xstate.after") === 0
```
to this
```js
 if (
        sendAction.event.type &&
        sendAction.event.type.indexOf("xstate.after") === 0
      ) {
        return null;
      }
```
in `src/StateChartAction.tsx` line 97

**Comment by sesm** [comment]
Encountered the same issue, and the fix above solved it. Created a PR
