### ISSUE TITLE
Where to find my saved 'viz'

### ISSUE THREAD

**Issue by mapicard** [statecharts/xstate-viz#58]
XState and this Visualizer is so cool, thanks a lot for these tools.
Not that long ago I had to write VBA macros in microsoft Visio to generate ObjectiveC code for my machine !!! 
The only thing though, I need to be logged in to save a machine, but when I'm logged in, where can I find my saved machines ???

**Comment by davidkpiano** [comment]
Hey thanks! You can find them on https://gist.github.com
