### ISSUE TITLE
Prominently add an open source license.

### ISSUE THREAD

**Issue by RyanMcG** [statecharts/xstate-viz#6]
@davidkpiano thank you for making this code available.

The `package.json` has license: MIT, but I think it would be ideal if the full MIT license text was included in source code somewhere too (e.g. a `LICENSE` file).

I am not a lawyer. I am not sure if this is strictly necessary but it is a very common practice (one  https://github.com/davidkpiano/xstate follows).

**Comment by davidkpiano** [comment]
I'd be happy to accept a PR for this.
