### ISSUE TITLE
cannot find module 'xstate/lib/graph'

### ISSUE THREAD

**Issue by goldenratio** [statecharts/xstate-viz#62]
Hi,
I am trying to run the build locally, getting this error. 

cannot find module 'xstate/lib/graph'
https://github.com/statecharts/xstate-viz/blob/master/src/StateChart.tsx#L22

Realized I need to change import to @xstate/graph, but it doesn't have `getEdges` function

**Comment by davidkpiano** [comment]
This is not meant to be consumed publicly. Please wait for the `@xstate/viz` package.

**Comment by philscrace2** [comment]
Appears as thought there is a breaking change on sha-221a0 or sha-b4be1 - If you update to sha-aa9f5, set the package.json to  "xstate": "4.6.7" without the ^, force the install of the xstate version like this 'npm install --save --save-exact react', then npm i react-scripts, then npm i, then npm run develop. Once the browser loads fix the URL to http://localhost:3000/. Visualizer now runs :) :) :) Will work out why this gets broken and then report. If the author needs help then shout but don't drop support for this great visualizer. You've done a really good job but ask for help if you need it.

**Comment by philscrace2** [comment]
It's the minor version change from 4.6.7 -> 4.7.0-rc1 that causes the breaking change. @davidkpiano how do I match versions to git-sha's? npm repository does not show me the correspondence between those two things and the releases are not labelled in the source tree

**Comment by philscrace2** [comment]
It's the minor version change from 4.6.7 -> 4.7.0-rc1 that causes the breaking change.
