### ISSUE TITLE
TypeError: m is not a function; there are no delays declarations

### ISSUE THREAD

**Issue by hamboomger** [statecharts/xstate-viz#89]
Since there are no delays declarations, I don't think it's related to https://github.com/statecharts/xstate-viz/issues/34.
Here's a [code snippet of machine](https://gist.github.com/hamboomger/ff17029aef057c916d2a96a30966d9e2)
Error:
```
TypeError: m is not a function
    at StateChartNode.js:191
    at Array.map (<anonymous>)
    at e.render (StateChartNode.js:176)
```

**Comment by davidkpiano** [comment]
We're working on updating the visualizer.

Please use the [XState inspector (CodeSandbox template)](https://codesandbox.io/s/xstate-viz-template-f3dtr) instead.

More info: https://xstate.js.org/docs/packages/xstate-inspect/
